name: Create MTG SQLite DB
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  create-db:
    name: Create MTG SQLite DB for Better Deck Builder
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Get Time
        run: echo "NOW=$(date +'%Y-%m-%dT%H.%M.%S')" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Create Card DB
        run: |
          python3 tools/createDB.py

      - name: Download Previous PHash
        run: |
          wget https://github.com/GavinDistaso/BetterDeckBuilder/releases/latest/download/MtgPHashes.sqlite 

      - name: Create/ Update PHash DB
        env:
          USR: ${{ secrets.USR }}
          PASS: ${{ secrets.PASS }}
        run: |
          python3 -m pip install pillow
          python3 -m pip install numpy
          python3 tools/mtgPHashDB.py

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: "AllPrintings.sqlite,MtgCHashes.sqlite"
            body: Database created at ${{ env.NOW }}.
            tag: ${{env.NOW}}
