name: Upload Pages

on:
  push:
    branches:
      - main
  workflow_run:
        workflows: ['Create MTG SQLite DB']
        types: [completed]
        branches:
            - 'main'
  workflow_dispatch:


jobs:
  upload-pages:
    name: Upload site to GH Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download DB
        run: |
          wget https://github.com/GavinDistaso/BetterDeckBuilder/releases/latest/download/AllPrintings.sqlite

      - name: Minify JS
        run: |
          npm install terser -g
          python tools/compressJS.py

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@5.0.0

      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./"

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: upload-pages

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
       
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
